# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fb8a4405dc38c828734af73f59877a37dfa20c478e9492fe86d4e605f0adcc8c2910f6f02d14ccba5129224b33d5d750a2ff95315ac67f81f9bea700a2cabb0b

test:
  secret_key_base: 8ae5d0b0da5c11a1b155132714d2a0fa03f01dd099ffa6599631d2d2a9073932bc724186f8485502c02b0c582cd7cb6079d83702909d136a340bf096a41879cb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
